# Generated by Django 4.0.5 on 2022-06-24 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0002_remove_teacher_name_teacher_teacher_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='image_url',
            field=models.URLField(default=1, verbose_name='Image URL'),
            preserve_default=False,
        ),
    ]
