# Generated by Django 4.0.5 on 2022-06-24 00:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0003_teacher_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='teacher_name',
        ),
        migrations.AddField(
            model_name='lesson',
            name='teacher',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='teacher_info', to='lessons.teacher', verbose_name='Professor(a)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lesson',
            name='video_url',
            field=models.URLField(verbose_name='Video Url'),
        ),
    ]
