# Generated by Django 4.0.5 on 2022-06-24 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0005_alter_lesson_options_alter_teacher_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='teacher',
        ),
        migrations.AddField(
            model_name='teacher',
            name='lesson',
            field=models.ManyToManyField(related_name='lessons', to='lessons.lesson'),
        ),
    ]
