# Generated by Django 4.0.5 on 2022-06-25 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0007_remove_teacher_lesson_teacher_lesson'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='lesson',
        ),
        migrations.AddField(
            model_name='lesson',
            name='teacher',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='lessons.teacher', verbose_name='teacher_info'),
            preserve_default=False,
        ),
    ]
