# Generated by Django 4.0.5 on 2022-06-26 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0010_remove_lesson_video_url_lesson_video_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='title',
            field=models.CharField(max_length=255, unique=True, verbose_name='Titulo'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='video_id',
            field=models.CharField(max_length=255, unique=True, verbose_name='Video ID'),
        ),
    ]
