# Generated by Django 4.0.5 on 2022-06-26 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0011_alter_lesson_slug_alter_lesson_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='video_id',
            field=models.CharField(max_length=255, verbose_name='Video ID'),
        ),
    ]
