# Generated by Django 4.0.5 on 2022-06-26 02:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0012_alter_lesson_video_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='video_id',
        ),
    ]
